; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-display-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lilygo-t-display-s3
framework = arduino

; Default build type is release, uncomment the following line to enable debug build
;build_type = debug

; On macOS with the LILYGO T-Display S3, only the following debug tool works.
debug_tool = esp-builtin
debug_init_break = tbreak setup
upload_protocol = esptool
upload_speed = 921600

monitor_speed = 115200

; Board configuration
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; Build flags
build_flags =
    -D BME280_I2C=1
;    -D BME280_SPI=1
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

; Debug flags
debug_flags =
    -DDEBUG_ESP_PORT=Serial
    -DDEBUG_ESP_CORE=1
    -DDEBUG_ESP_WIFI=0
    -DDEBUG_ESP_HTTP_CLIENT=0
    -DDEBUG_ESP_HTTP_SERVER=0
    -DDEBUG_ESP_TLS=0
    -O3
    -g3
    
; Library dependencies
lib_deps =
    moononournation/GFX Library for Arduino
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor